server {
    listen 80;

    # 1. Frontend: Servir los archivos de React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Vital para aplicaciones React (SPA)
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy inverso hacia el Backend de Ventas
    # Usamos el nombre del Service de Kubernetes como host
    location /api/ventas/ {
        proxy_pass http://backend-ventas-svc:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Proxy inverso hacia el Backend de Despachos
    location /api/despachos/ {
        proxy_pass http://backend-despachos-svc:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}