version: '3.8'

services:
  ventas-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_ventas
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

  despachos-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_despachos
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"

  service-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=ventas-db
      - DB_PORT=3306
      - DB_NAME=db_ventas
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - ventas-db

  service-despachos:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=despachos-db
      - DB_PORT=3306
      - DB_NAME=db_despachos
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - despachos-db

  frontend:
    build: ./front_despacho
    ports:
      - "5173:5173"
    depends_on:
      - service-ventas
      - service-despachos